language: node_js
node_js:
  - 0.10
notifications:
    email: false
    irc:
        channels:
          - "irc.macak.co.uk#hackthis-dev"
        template:
          - "%{repository}#%{build_number} (%{branch} - %{commit}): %{message}"
